## YAML Template.
version: '3'
services:
  ## Data base Setup
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: 'sigap'
      POSTGRES_USER: 'sigap'
      POSTGRES_PASSWORD: 'sigap'
    ports:
      - "5433:5432"
    expose:
      - "5432"
    volumes:
      - sigap_db:/var/lib/postgresql/data
    networks:
      - sigap_network

  ## Backend Setup
  server:
    depends_on:
      - db
    image: ccr.mef/caisff/sigap
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: 'prod'
      SPRING_DATASOURCE_USERNAME: 'sigap'
      SPRING_DATASOURCE_PASSWORD: 'sigap'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/sigap'

    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - sigap_network

networks:
  sigap_network:
volumes:
  sigap_db:

