apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: k8s-formation
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/test/db"
  persistentVolumeReclaimPolicy: Retain


