apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: k8s-formation
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

