apiVersion: v1
kind: Secret
metadata:
  name: my-db-secret
#  namespace: k8s-formation
data:
  username: bXktdXNlcg==
  user_password: bXktdXNlci1wYXNzd29yZA==
  root_password: bXktYWRtaW4tcGFzc3dvcmQ=



