apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset01
  labels:
    app: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      name: my-pod
      labels:
        app: test
    spec:
      containers:
        - name: test-container
          image: nginx

