apiVersion: v1
kind: Pod
metadata:
  name: my-pod01
spec:
  containers:
    - name: test-container
      image: nginx
      resources:
        requests:
          memory: '30Mi'
          cpu: '10m'
        limits:
          memory: '100Mi'
          cpu: '20m'

