apiVersion: v1
kind: Pod
metadata:
  name: my-pod01
spec:
  containers:
    - name: test-container
      image: nginx
      livenessProbe:
        httpGet:
          port: 80
      #          path: '/test'
      #        initialDelaySeconds: 5
      #        periodSeconds: 5
      #        failureThreshold: 10
      readinessProbe:
        httpGet:
          port: 80
#          path: '/'
#        initialDelaySeconds: 5
#        periodSeconds: 5

#        exec:
#          command:
#            - <cmd>
