apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:
  file1: |
    Bonjour Je suis un fichier depuis un Config Map
  fileHtml: |
    <html>
      <body>
        <h1>Bonjour tout le monde</h1>
      </body>
    </html>
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod01
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
        - mountPath: /test/files
          name: volume-cm
  volumes:
    - name: volume-cm
      configMap:
        name: my-config-map
        items:
          - key: file1
            path: my-file.txt
          - key: fileHtml
            path: index.html
