apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  key1: c2VjcmV0MQ==
  key2: c2VjcmV0Mg==
  key3: c2VjcmV0MyBzZWNyZXQzICBzZWNyZXQzIHNlY3JldDM=
  fileScret: |
    VW4gZ3JvcyBzZWNyZXQgYSBuZSBwYXMgZGV2b2xlcg==
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod01
spec:
  containers:
    - name: test-container
      ports:
        - containerPort: 80
          hostPort: 90
      image: nginx
      env:
        - name: ENV1
          value: ENV1
        - name: ENV_KEY1
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: key1
        - name: ENV_KEY2
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: key2
        - name: ENV_KEY3
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: key3
      volumeMounts:
        - mountPath: /test/config
          name: my-volume-from-secret
  volumes:
    - name: my-volume-from-secret
      secret:
        secretName: my-secret
        items:
          - key: fileScret
            path: config.txt
