apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment01
  labels:
    app: test
    app.kubernetes.io/version: "1.19"
#    app.kubernetes.io/version: 1.19
#    app.kubernetes.io/version: 1.19
spec:
  replicas: 3
#  replicas: 20
#  minReadySeconds: 2
#  progressDeadlineSeconds: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      name: my-pod
      labels:
        app: test
    spec:
      containers:
        - name: test-container
          image: nginx:1.19
#          image: nginx:1.20
#          image: nginx:1.21
