apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-deploy
  labels:
    app: my-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pod
      stack: spring
  template:
    metadata:
      name: my-spring-pod
      labels:
        app: my-pod
        stack: spring
    spec:
      containers:
        - name: my-spring-pod
          image: k8s-spring:0.0.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-deploy
  labels:
    app: my-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pod
      stack: node
  template:
    metadata:
      name: my-node-pod
      labels:
        app: my-pod
        stack: node
    spec:
      containers:
        - name: my-node-pod
          image: k8s-node:0.0.1
          env:
            - name: SERVER_PORT
              value: '8080'
---
apiVersion: v1
kind: Service
metadata:
  name: my-node-service
  labels:
    app: my-node-service
spec:
  type: NodePort
  selector:
    app: my-pod
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
